In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
my_dataframe = pd.read_excel('1.xlsx')
my_dataframe

1      2      3
0  3.777  3.651  3.651
1  4.940  1.512  1.008
2  7.450  2.251  1.424

Преобразуем нашу платежную матрицу

In [3]:
my_new_matrix = 10 - my_dataframe
my_new_matrix

1      2      3
0  6.223  6.349  6.349
1  5.060  8.488  8.992
2  2.550  7.749  8.576

In [4]:
np.array([list(my_new_matrix.max(axis = 1))]).T

array([[6.349],
       [8.992],
       [8.576]])

Создадим матрицу рисков

In [5]:
my_risk = np.array(np.array([list(my_new_matrix.max(axis = 1))]).T - np.array(my_new_matrix))
pd.DataFrame(my_risk)

0      1    2
0  0.126  0.000  0.0
1  3.932  0.504  0.0
2  6.026  0.827  0.0

In [6]:
p1 = 0.2
p2 = 0.5
p3 = 1-p1-p2

In [7]:
mat = my_new_matrix*[p1,p2,p3]
mat

1       2       3
0  1.2446  3.1745  1.9047
1  1.0120  4.2440  2.6976
2  0.5100  3.8745  2.5728

In [8]:
pd.DataFrame(mat.sum(axis = 1))

0
0  6.3238
1  7.9536
2  6.9573

In [9]:
my_seriess = mat.sum(axis = 1)
my_seriess

0    6.3238
1    7.9536
2    6.9573
dtype: float64

In [10]:
f"Исходя из матрицы мат ожидания видно, что {my_seriess.argmax()+1} вариант нам подходит"

'Исходя из матрицы мат ожидания видно, что 2 вариант нам подходит'

 Решим с помощью матрицы рисков

In [11]:
r1 = my_risk*[p1,p2,p3]
r1.sum(axis = 1)

array([0.0252, 1.0384, 1.6187])

In [12]:
pd.DataFrame(my_risk)

0      1    2
0  0.126  0.000  0.0
1  3.932  0.504  0.0
2  6.026  0.827  0.0

In [13]:
f"Исходя из матрицы рисков видно, что {r1.sum(axis = 1).argmin()+1} является самым надежным"

'Исходя из матрицы рисков видно, что 1 является самым надежным'

In [14]:
laplas = 1/3*my_new_matrix.sum(axis = 1)
laplas 

0    6.307000
1    7.513333
2    6.291667
dtype: float64

In [15]:
f"На основании недостаточности основания Лапласса принимаем вариант {laplas.argmax()+1}"

'На основании недостаточности основания Лапласса принимаем вариант 2'

Критерий Вальда

In [16]:
pd.DataFrame(my_new_matrix)

1      2      3
0  6.223  6.349  6.349
1  5.060  8.488  8.992
2  2.550  7.749  8.576

In [17]:
W = my_new_matrix.min(axis = 1)
W

0    6.223
1    5.060
2    2.550
dtype: float64

In [18]:
f"По критерию Вальда {W.argmax()+1} вариант проходит"

'По критерию Вальда 1 вариант проходит'

Принимаем решение по критерию Сэвиджа

In [19]:
pd.DataFrame(my_risk)

0      1    2
0  0.126  0.000  0.0
1  3.932  0.504  0.0
2  6.026  0.827  0.0

In [20]:
Savige = my_risk.max(axis = 1)
Savige

array([0.126, 3.932, 6.026])

In [21]:
f"По критерию Сэвиджа {Savige.argmin()+1} вариант проходит"

'По критерию Сэвиджа 1 вариант проходит'

Определяем по критерию Гурвица

In [22]:
 a = [0.1 * i for i in range(11)]

In [23]:
H = [max(a[i]*my_new_matrix.min(axis=1) + (1-a[i])*my_new_matrix.max(axis=1)) for i in range(len(a))]
H

[8.992,
 8.5988,
 8.2056,
 7.8124,
 7.4192,
 7.026,
 6.6328,
 6.2608,
 6.248200000000001,
 6.2356,
 6.223]

In [24]:
[(a[i]*my_new_matrix.min(axis=1) + (1-a[i])*my_new_matrix.max(axis=1)).argmax()+1 for i in range(len(a))]

[2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1]

In [25]:
df = pd.DataFrame({
    "a":a,
    "Значение H" :H,
    "Номер выгодной стратегии":[(a[i]*my_new_matrix.min(axis=1) + (1-a[i])*my_new_matrix.max(axis=1)).argmax()+1 for i in range(len(a))]
})

In [26]:
df

a  Значение H  Номер выгодной стратегии
0   0.0      8.9920                         2
1   0.1      8.5988                         2
2   0.2      8.2056                         2
3   0.3      7.8124                         2
4   0.4      7.4192                         2
5   0.5      7.0260                         2
6   0.6      6.6328                         2
7   0.7      6.2608                         1
8   0.8      6.2482                         1
9   0.9      6.2356                         1
10  1.0      6.2230                         1

Исходя из лабораторной работы, получаем, что вариант 2 является самым оптимальным