# Лабораторная работа №3

In [1]:
import pandas as pd 
import numpy as np

p1 = [0.1,0.2,0.3,0.4]
a  = [0.7,0.4,0.2,0.1]

d = [2,4,6,8]

Пропишем исходные функции

In [2]:
Z = lambda d:-0.008*d**3+0.4*d**2 - 5.97*d + 68.3
Yo = lambda d:-0.001*d**3+0.07*d**2 + 0.88*d + 0.63
Yd = lambda d: 0.001*d**3-0.02*d**2 + 0.09*d - 0.08

In [3]:
final_function = lambda a,d : Z(d) + (1-a)*Yo(d) + a*Yd(d)

Создадим платежную матрицу

In [4]:
my_pay_matrix = np.zeros([4,4])
for i in range(len(a)):
    for j in range(len(a)):
         my_pay_matrix[i,j] = final_function(a[j],d[i])

            
my_pay_matrix 

array([[58.7142, 59.5044, 60.0312, 60.2946],
       [51.8866, 53.4412, 54.4776, 54.9958],
       [47.5854, 50.0628, 51.7144, 52.5402],
       [45.4458, 48.9756, 51.3288, 52.5054]])



# Подберем по Условию Лапласса

In [5]:
laplas = my_pay_matrix * p1
laplas

array([[ 5.87142, 11.90088, 18.00936, 24.11784],
       [ 5.18866, 10.68824, 16.34328, 21.99832],
       [ 4.75854, 10.01256, 15.51432, 21.01608],
       [ 4.54458,  9.79512, 15.39864, 21.00216]])

In [6]:
laplas.sum(axis =1)

array([59.8995, 54.2185, 51.3015, 50.7405])

In [7]:
f"Номер выигрышной стратегии {laplas.sum(axis =1).argmax()+1}"

'Номер выигрышной стратегии 1'

В условиях неопределенности

In [8]:
laplas = my_pay_matrix * [1/4]*4
laplas

array([[58.7142, 59.5044, 60.0312, 60.2946],
       [51.8866, 53.4412, 54.4776, 54.9958],
       [47.5854, 50.0628, 51.7144, 52.5402],
       [45.4458, 48.9756, 51.3288, 52.5054]])

In [9]:
laplas.sum(axis =1)

array([238.5444, 214.8012, 201.9028, 198.2556])

In [10]:
f"Номер выигрышной стратегии {laplas.sum(axis =1).argmax()+1}"

'Номер выигрышной стратегии 1'

# Реализуем алгоритм Вальда

In [11]:
vald = my_pay_matrix.min(axis = 1)
vald

array([58.7142, 51.8866, 47.5854, 45.4458])

In [12]:
f"Номер выигрышной стратегии {laplas.sum(axis =1).argmax()+1}"

'Номер выигрышной стратегии 1'

# Реализуем алгоритм Гурвица

In [13]:
a = [0.1 * i for i in range(11)]
H = [max(a[i]*my_pay_matrix.min(axis=1) + (1-a[i])*my_pay_matrix.max(axis=1)) for i in range(len(a))]
H

[60.2946,
 60.13656,
 59.97852,
 59.82048,
 59.662440000000004,
 59.504400000000004,
 59.34636,
 59.188320000000004,
 59.030280000000005,
 58.87224,
 58.7142]

In [14]:
df_1 = pd.DataFrame({
    "a":a,
    "Значение H" :H,
    "Номер выгодной стратегии":[(a[i]*my_pay_matrix.min(axis=1) + (1-a[i])*my_pay_matrix.max(axis=1)).argmax()+1 for i in range(len(a))]
})
df_1

a  Значение H  Номер выгодной стратегии
0   0.0    60.29460                         1
1   0.1    60.13656                         1
2   0.2    59.97852                         1
3   0.3    59.82048                         1
4   0.4    59.66244                         1
5   0.5    59.50440                         1
6   0.6    59.34636                         1
7   0.7    59.18832                         1
8   0.8    59.03028                         1
9   0.9    58.87224                         1
10  1.0    58.71420                         1

# Реализуем выбор по Сэвиджу

Создадим матрицу рисков


In [15]:
my_risk = 100 - my_pay_matrix
my_risk

array([[41.2858, 40.4956, 39.9688, 39.7054],
       [48.1134, 46.5588, 45.5224, 45.0042],
       [52.4146, 49.9372, 48.2856, 47.4598],
       [54.5542, 51.0244, 48.6712, 47.4946]])

In [16]:
max_risk = my_risk.max(axis =1)
max_risk

array([41.2858, 48.1134, 52.4146, 54.5542])

In [17]:
result = []
for i in range(len(max_risk)):
    result.append(abs(sum((my_risk[i]-max_risk[i]))))
np.array(result)

array([ 3.6876,  7.2548, 11.5612, 16.4724])

In [18]:
f"Номер выигрышной стратегии {np.array(result).argmin()+1}"

'Номер выигрышной стратегии 1'